PROJECT = Jean-Bot
#  
# CC 	= arm-none-eabi-gcc
# CCFLAGS = -Wall
# OBJS 	=
# LIB 	:= -L ../lib/e-puck_main-processor/src -I ../lib/e-puck_main-processor/src
# 
# main: $(OBJS) main.o
# 	$(CC) $^ -o Jean-Bot $(LIB)
# 
# clean:
# 	\rm $(OBJS) main.o Jean-Bot

CSRC += ./main.c

INCDIR +=

GLOBAL_PATH = ../lib/e-puck2_main-processor
include $(GLOBAL_PATH)/Makefile

